/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;


import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author gonzalez
 */
public class JInternalFrameCitasMedicas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameCitasMedicas
     */
    public JInternalFrameCitasMedicas() {
        initComponents();
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        IDCliente = new javax.swing.JLabel();
        IDDoctor = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        jTextHora = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboIDDoctor = new javax.swing.JComboBox<>();
        jComboIDCliente = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jTextFecha = new javax.swing.JFormattedTextField();

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IDCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IDCliente.setForeground(new java.awt.Color(51, 0, 240));
        IDCliente.setText("ID Cliente");
        jPanel2.add(IDCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 201, -1, -1));

        IDDoctor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IDDoctor.setForeground(new java.awt.Color(51, 0, 240));
        IDDoctor.setText("ID Doctor");
        jPanel2.add(IDDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 201, -1, -1));

        Fecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Fecha.setForeground(new java.awt.Color(51, 0, 240));
        Fecha.setText("Fecha");
        jPanel2.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 257, -1, -1));

        Hora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hora.setForeground(new java.awt.Color(51, 0, 240));
        Hora.setText("Hora");
        jPanel2.add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 257, -1, -1));
        jPanel2.add(jTextHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 259, 110, -1));

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(51, 0, 240));
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Guardar.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jButtonActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(51, 0, 240));
        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Actualizar.png"))); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/registros-medicos (1).png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Registrar");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Cita Médica");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jComboIDDoctor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboIDDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        jPanel2.add(jComboIDDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 202, 110, -1));

        jComboIDCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboIDCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        jPanel2.add(jComboIDCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 202, 110, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        try {
            jTextFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
      
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
    
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Fecha;
    public static javax.swing.JLabel Hora;
    public static javax.swing.JLabel IDCliente;
    public static javax.swing.JLabel IDDoctor;
    public static javax.swing.JButton jButtonActualizar;
    public static javax.swing.JButton jButtonGuardar;
    public static javax.swing.JComboBox<String> jComboIDCliente;
    public static javax.swing.JComboBox<String> jComboIDDoctor;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JFormattedTextField jTextFecha;
    public static javax.swing.JTextField jTextHora;
    // End of variables declaration//GEN-END:variables
}